table = [['ABCDEFGHIJKLMNOPQRSTUVWXYZ'],['BCDEFGHIJKLMNOPQRSTUVWXYZA'],['CDEFGHIJKLMNOPQRSTUVWXYZAB'],['DEFGHIJKLMNOPQRSTUVWXYZABC'],['EFGHIJKLMNOPQRSTUVWXYZABCD'],['FGHIJKLMNOPQRSTUVWXYZABCDE'],['GHIJKLMNOPQRSTUVWXYZABCDEF'],['HIJKLMNOPQRSTUVWXYZABCDEFG'],['IJKLMNOPQRSTUVWXYZABCDEFGH'],['JKLMNOPQRSTUVWXYZABCDEFGHI'],['KLMNOPQRSTUVWXYZABCDEFGHIJ'],['LMNOPQRSTUVWXYZABCDEFGHIJK'],['MNOPQRSTUVWXYZABCDEFGHIJKL'],['NOPQRSTUVWXYZABCDEFGHIJKLM'],['OPQRSTUVWXYZABCDEFGHIJKLMN'],['PQRSTUVWXYZABCDEFGHIJKLMNO'],['QRSTUVWXYZABCDEFGHIJKLMNOP'],['RSTUVWXYZABCDEFGHIJKLMNOPQ'],['STUVWXYZABCDEFGHIJKLMNOPQR'],['TUVWXYZABCDEFGHIJKLMNOPQRS'],['UVWXYZABCDEFGHIJKLMNOPQRST'],['VWXYZABCDEFGHIJKLMNOPQRSTU'],['WXYZABCDEFGHIJKLMNOPQRSTUV'],['XYZABCDEFGHIJKLMNOPQRSTUVW'],['YZABCDEFGHIJKLMNOPQRSTUVWX'],['ZABCDEFGHIJKLMNOPQRSTUVWXY']]
ind = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
key = 'lemon'
alphabet = ''
def encode(self, text):
    #sets up the index numbers of each character in self (column numbers)
    selfind = [ind.index(char.upper()) for char in list(self)]
    #sets up the index numbers of each character in key (row numbers)
    keyind = [ind.index(key.upper()) for char in list(key)]
    encoded = [table[keyind][selfind] for char in list(self) for char in list(key)]
    return ''.join(encoded)